repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
  - id: check-json
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
- repo: https://github.com/JohnnyMorganz/StyLua
  rev: v0.12.4
  hooks:
  - id: stylua-system
- repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: v1.1.13
  hooks:
  - id: remove-crlf
  - id: forbid-tabs
- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v13.0.1
  hooks:
  - id: clang-format
- repo: local
  hooks:
  - id: build-and-test
    name: build and test
    entry: sh -c "luarocks build --no-install && busted"
    language: system
    pass_filenames: false
  - id: luacheck
    name: luacheck
    entry: luacheck .
    language: system
    types: [lua]
- repo: meta
  hooks:
  - id: check-hooks-apply
  - id: check-useless-excludes
