describe('wowrender/magick', function()
  local t = require('wowrender.magick')
  it('loads', function()
    assert.same('table', type(t))
  end)
  it('works', function()
    local wand = t:new_magick_wand()
    assert.True(wand:read_image('magick:logo'))
    assert.same('GIF', wand:get_image_format())
    assert.same(480, wand:get_image_height())
    assert.same(640, wand:get_image_width())
  end)
end)
