name: test
on:
  pull_request:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-buildx-action@v1
    - name: build devcontainer image
      uses: docker/build-push-action@v2
      with:
        cache-from: type=gha
        cache-to: type=gha,mode=max
        file: .devcontainer/Dockerfile
        load: true
        tags: moo
    - name: run tests in devcontainer
      run: docker run -t -v $PWD:/moo moo bash -c "cd /moo && pre-commit run -a"
